#pragma once

//!
//! @file iffl_config.h
//!
//! @author Vladimir Petter
//!
//! [iffl github](https://github.com/vladp72/iffl) 
//!
//! @brief This file is supposed to be generated by cmake.
//!        Cmake pushes output to the folder where it generates project.
//!        It is not clear t me at the moment how I can publish and install this file from there.
//!

//!
//! @brief Intrusive flat forward list library major version number
//!
#define IFFL_VERSION_MAJOR (1)
//!
//! @brief Intrusive flat forward list library minor version number
//!
#define IFFL_VERSION_MINOR (3)
//!
//! @brief Intrusive flat forward list library patch version number
//!
#define IFFL_VERSION_PATCH (4)
